### PR TITLE
PR 1.6.0

### PR DESCRIPTION
**Pull request by LausiD**
and ready for Latest

### CODE REVIEW

**Comment by Apollon77** [comment]
should I check and merge?

**Comment by LausiD** [comment]
Yes, please:-)Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Ingo Fischer ***@***.***> Datum: 09.04.21  13:45  (GMT+01:00) An: "iobroker-community-adapters/ioBroker.fhem" ***@***.***> Cc: LausiD ***@***.***>, Author ***@***.***> Betreff: Re: [iobroker-community-adapters/ioBroker.fhem] PR 1.6.0 (#105) 
should I check and merge?

**Comment by Apollon77** [comment]
Ok, I added some stuff and will relelase soon

**Comment by Apollon77** [comment]
release running via Github actions now ... in future please do not increase version numbers in packag/io-package, just add in readme a new section like https://github.com/iobroker-community-adapters/ioBroker.fhem/commit/ec05be63043b537afd8e82d7d0ddf23cc479d35c#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R49 and tell if patch, minot or major release ... rest is done by script

**Comment by LausiD** [comment]
Thanks a lot!

**Pull request merged**
